repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.9.1  # Use the version that matches the one in your pyproject.toml
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the version that matches the one in your pyproject.toml
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/pylint
    rev: v3.0.0a7  # Use the version that matches the one in your pyproject.toml
    hooks:
    -   id: pylint
